import type { SideboardMatrixProps } from "@/components/blog/SideboardMatrix";

export const title = "Golgari Airship: Sideboard Matrix";

export const matrix: SideboardMatrixProps = {
  sideboardCards: [
    { name: "Day of Black Sun", count: 2 },
    { name: "Day of Judgment", count: 1 },
    { name: "Duress", count: 4 },
    { name: "Intimidation Tactics", count: 2 },
    { name: "Pawpatch Formation", count: 1 },
    { name: "Shoot the Sheriff", count: 1 },
    { name: "Soul-Guide Lantern", count: 2 },
    { name: "The Ooze", count: 1 },
    { name: "Urgent Necropsy", count: 1 },
  ],
  maindeckCards: [
    { name: "Badgermole Cub", count: 4 },
    { name: "Beseech the Mirror", count: 4 },
    { name: "Bitter Triumph", count: 1 },
    { name: "Deep-Cavern Bat", count: 2 },
    { name: "Elegy Acolyte", count: 1 },
    { name: "Gene Pollinator", count: 4 },
    { name: "Leatherhead, Swamp Stalker", count: 1 },
    { name: "Llanowar Elves", count: 2 },
    { name: "Mutagen Man, Living Ooze", count: 3 },
    { name: "Obsessive Pursuit", count: 4 },
    { name: "Phoenix Fleet Airship", count: 1 },
    { name: "Requiting Hex", count: 1 },
    { name: "Sentinel of the Nameless City", count: 2 },
    { name: "The Witch's Vanity", count: 2 },
    { name: "Tragic Trajectory", count: 3 },
    { name: "Swamp", count: 4 },
  ],
  matchups: [
    {
      name: "Momo",
      link: "https://melee.gg/Decklist/View/504207bb-f752-487d-aba1-b40500c526fc",
      colors: ["W"],
      in: {
        "Pawpatch Formation": 1,
        "Day of Black Sun": 2,
        "Day of Judgment": 1,
        "Intimidation Tactics": 2,
      },
      out: {
        "Sentinel of the Nameless City": 2,
        "Leatherhead, Swamp Stalker": 1,
        "Llanowar Elves": 2,
        "Bitter Triumph": 1,
      },
    },
    {
      name: "Aggro",
      link: "https://melee.gg/Decklist/View/4aee1083-e72a-4635-acf7-b401008e18bf",
      colors: ["R"],
      in: {
        "Intimidation Tactics": 2,
        "Day of Black Sun": 2,
        "Shoot the Sheriff": 1,
      },
      out: {
        "Llanowar Elves": 2,
        "Phoenix Fleet Airship": 1,
        "Deep-Cavern Bat": 2,
      },
    },
    {
      name: "Landfall",
      link: "https://melee.gg/Decklist/View/0c09e6a0-37ec-43b8-babc-b405015feedb",
      colors: ["G"],
      in: {
        Duress: 1,
        "Intimidation Tactics": 2,
        "Day of Black Sun": 2,
        "The Ooze": 1,
      },
      out: {
        "Requiting Hex": 1,
        "The Witch's Vanity": 2,
        "Sentinel of the Nameless City": 2,
        "Leatherhead, Swamp Stalker": 1,
      },
    },
    {
      name: "Tempo",
      link: "https://melee.gg/Decklist/View/3474214e-22e5-48ee-ac72-b4050160b0a5",
      colors: ["W", "U"],
      in: {
        "Pawpatch Formation": 1,
        "Intimidation Tactics": 2,
        "Urgent Necropsy": 1,
      },
      out: {
        "Sentinel of the Nameless City": 1,
        "The Witch's Vanity": 2,
        "Requiting Hex": 1,
      },
    },
    {
      name: "Dragons",
      link: "https://melee.gg/Decklist/View/9c1f26e9-2533-4a7b-81a7-b3c200e62c2d",
      colors: ["W", "R"],
      in: {
        "Pawpatch Formation": 1,
        "Intimidation Tactics": 2,
        "Day of Judgment": 1,
        "Shoot the Sheriff": 1,
      },
      out: { "Deep-Cavern Bat": 2, "Llanowar Elves": 2, "Requiting Hex": 1 },
    },

    {
      name: "Excruciator",
      link: "https://melee.gg/Decklist/View/d5786302-fe72-4578-8f26-b40600977991",
      colors: ["U", "B"],
      in: { "Intimidation Tactics": 2, Duress: 4, "The Ooze": 1 },
      out: {
        "Requiting Hex": 1,
        "Tragic Trajectory": 3,
        "Bitter Triumph": 1,
        "The Witch's Vanity": 2,
      },
    },
    {
      name: "Midrange",
      link: "https://melee.gg/Decklist/View/4ae3cdca-c5d9-4eae-a6d2-b402015bb0ef",
      colors: ["U", "B"],
      in: { "Intimidation Tactics": 2, Duress: 2 },
      out: { "Sentinel of the Nameless City": 2, "Deep-Cavern Bat": 2 },
    },
    {
      name: "Spellementals",
      link: "https://melee.gg/Decklist/View/4d153a5d-ec98-4b53-bcd0-b405001ae5a6",
      colors: ["U", "R"],
      in: { Duress: 4, "Soul-Guide Lantern": 2, "The Ooze": 1 },
      out: {
        "Deep-Cavern Bat": 2,
        "Leatherhead, Swamp Stalker": 1,
        "Requiting Hex": 1,
        "The Witch's Vanity": 2,
        "Tragic Trajectory": 1,
      },
    },
    {
      name: "Prowess",
      link: "https://melee.gg/Decklist/View/df8250da-abb4-497a-aa62-b3fd012fad18",
      colors: ["U", "R"],
      in: {
        Duress: 4,
        "The Ooze": 1,
        "Day of Black Sun": 2,
        "Pawpatch Formation": 1,
        "Shoot the Sheriff": 1,
      },
      out: {
        "Gene Pollinator": 2,
        "Beseech the Mirror": 4,
        "Phoenix Fleet Airship": 1,
        "Leatherhead, Swamp Stalker": 1,
        Swamp: 1,
      },
    },
    {
      name: "Lessons",
      link: "https://melee.gg/Decklist/View/0dd4c7bd-8481-48d2-b520-b40501853516",
      colors: ["U", "R"],
      in: {
        "Soul-Guide Lantern": 2,
        "The Ooze": 1,
        "Urgent Necropsy": 1,
        Duress: 4,
      },
      out: {
        "Deep-Cavern Bat": 2,
        "Tragic Trajectory": 2,
        "Llanowar Elves": 2,
        "Elegy Acolyte": 1,
        "Bitter Triumph": 1,
      },
    },
    {
      name: "Rhythm",
      link: "https://melee.gg/Decklist/View/d23f523f-6364-49a1-a692-b40501462556",
      colors: ["U", "G"],
      in: {
        "Intimidation Tactics": 2,
        "Day of Black Sun": 2,
        "Day of Judgment": 1,
      },
      out: {
        "Leatherhead, Swamp Stalker": 1,
        "Sentinel of the Nameless City": 2,
        "Llanowar Elves": 2,
      },
    },
    {
      name: "Discard",
      link: "https://melee.gg/Decklist/View/41172219-c5e6-4c7f-a7a0-b405014ba6c1",
      colors: ["B", "R"],
      in: {
        "Urgent Necropsy": 1,
        "The Ooze": 1,
        "Intimidation Tactics": 2,
        "Day of Black Sun": 1,
      },
      out: {
        "Bitter Triumph": 1,
        "Leatherhead, Swamp Stalker": 1,
        "Deep-Cavern Bat": 2,
        "Llanowar Elves": 1,
      },
    },
    {
      name: "Grixis",
      link: "https://melee.gg/Decklist/View/6721a84e-f15a-4962-8958-b4050007fe54",
      colors: ["U", "B", "R"],
      in: {
        "Urgent Necropsy": 1,
        "The Ooze": 1,
        "Intimidation Tactics": 2,
        "Day of Black Sun": 1,
      },
      out: {
        "Bitter Triumph": 1,
        "Leatherhead, Swamp Stalker": 1,
        "Deep-Cavern Bat": 2,
        "Llanowar Elves": 1,
      },
    },
    {
      name: "Control",
      link: "https://melee.gg/Decklist/View/bcb0c7ad-27fb-4b27-9c14-b4060010466d",
      colors: ["W", "U", "R"],
      in: { Duress: 4, "Pawpatch Formation": 1, "Intimidation Tactics": 1 },
      out: {
        "Requiting Hex": 1,
        "Tragic Trajectory": 3,
        "The Witch's Vanity": 2,
      },
    },
    {
      name: "Airbending",
      link: "https://melee.gg/Decklist/View/0f79e594-91fe-4c08-bf80-b405018a1ed1",
      colors: ["W", "U", "G"],
      in: {
        "Pawpatch Formation": 1,
        "Intimidation Tactics": 2,
        "Day of Judgment": 1,
      },
      out: {
        "Elegy Acolyte": 1,
        "Leatherhead, Swamp Stalker": 1,
        "Llanowar Elves": 2,
      },
    },
    {
      name: "Reanimator",
      link: "https://melee.gg/Decklist/View/46f4fb72-47a2-4cd1-b1f3-b405004e7b9f",
      colors: ["U", "B", "G"],
      in: {
        "Intimidation Tactics": 2,
        Duress: 1,
        "Soul-Guide Lantern": 2,
        "The Ooze": 1,
      },
      out: {
        "Requiting Hex": 1,
        "The Witch's Vanity": 2,
        "Tragic Trajectory": 3,
      },
    },
    {
      name: "Harmonizer",
      link: "https://melee.gg/Decklist/View/882b3d60-723c-4697-8cae-b4060028606a",
      colors: ["U", "R", "G"],
      in: { Duress: 4, "Intimidation Tactics": 2, "The Ooze": 1 },
      out: {
        "Requiting Hex": 1,
        "The Witch's Vanity": 2,
        "Elegy Acolyte": 1,
        "Tragic Trajectory": 1,
        "Sentinel of the Nameless City": 2,
      },
    },
  ],
};
